# Generated by Django 5.2.10 on 2026-02-17 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp_alter_groupinvite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='person_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.personidentity'),
        ),
        migrations.AddField(
            model_name='personidentity',
            name='placeholder_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placeholder_identity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('placeholder', 'Placeholder')], default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identities', to=settings.AUTH_USER_MODEL),
        ),
    ]
