# Generated by Django 5.2.10 on 2026-02-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupmembership_person_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('placeholder', 'Placeholder')], default='accepted', max_length=20),
        ),
    ]
