# Generated by Django 5.2.10 on 2026-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_phoneotp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
