# Generated by Django 5.2.11 on 2026-03-02 08:37

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Profile = apps.get_model('core', 'Profile')

    existing_profile_user_ids = set(Profile.objects.values_list('user_id', flat=True))
    missing_profiles = [
        Profile(user_id=user_id)
        for user_id in User.objects.exclude(id__in=existing_profile_user_ids).values_list('id', flat=True)
    ]
    if missing_profiles:
        Profile.objects.bulk_create(missing_profiles)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
